MODEL_CONFIG = {
    "weight":{
        "protein": "poc_pre_220816.pt",
        "molecule_no_h": "mol_pre_no_h_220816.pt",
        "molecule_all_h": "mol_pre_all_h_220816.pt",
        "crystal": "mp_all_h_230313.pt",
        "mof": "mof_pre_no_h_CORE_MAP_20230505.pt",
        "oled": "oled_pre_no_h_230101.pt",
        "peptide_monomer": "peptide_monomer_240121.pt",
        "peptide_dimer_random": "peptide_dimer_0122_random.pt",
        "peptide_dimer_mannual": "peptide_dimer_0122_mannual.pt",
        "peptide_dimer_random_new": "peptide_dimer_0127_random.pt",
    },
    "dict":{
        "protein": "poc.dict.txt",
        "molecule_no_h": "mol.dict.txt",
        "molecule_all_h": "mol.dict.txt",
        "crystal": "mp.dict.txt",
        "mof": "mof.dict.txt",
        "oled": "oled.dict.txt",
        "peptide_monomer": "peptide_monomer.dict.txt",
        "peptide_dimer_random": "peptide_dimer.dict.txt",
        "peptide_dimer_mannual": "peptide_dimer.dict.txt",
        "peptide_dimer_random_new": "peptide_dimer.dict.txt",
    },
}