#!/bin/csh


# Creating standard MARTINI topology files.
# python martini.py -f 3f7v.pdb -o system.top -x cg.pdb -dssp dssp -p backbone -ff martini22

#
# Creating a file containing additional parameter set for TM1 helix of chain A of KcsA.
python hinge.py  3f7v.pdb  Protein_A.itp  A  30  52  >  chainA_TM1_param.itp

#
# Creating a file containing additional parameter set for P-helix of chain A of KcsA.
python hinge.py  3f7v.pdb  Protein_A.itp  A  62  74  >  chainA_P-helix_param.itp

#
# Creating a file containing additional parameter set for TM2 of chain A of KcsA.
python hinge.py  3f7v.pdb  Protein_A.itp  A  86  116  >  chainA_TM2_param.itp

#
# Combination new parameter sets of all TM helices of chain A of KcsA.
cat chainA_TM1_param.itp chainA_P-helix_param.itp chainA_TM2_param.itp > chainA_param.itp 

#
# To merge chainA_param.itp into the standard topology Protein_A_P.itp.
python  insert_param.py  Protein_A.itp  chainA_param.itp

#
# To obtain the combined topology files for all the other subunits of KcsA including new_Protein_B.itp, new_Protein_C.itp and new_Protein_D.itp.
for chn in B C D
do
  echo $chn
  python hinge.py  3f7v.pdb  Protein_${chn}.itp  $chn  30  52  >  chain${chn}_TM1_param.itp
  python hinge.py  3f7v.pdb  Protein_${chn}.itp  $chn  62  74  >  chain${chn}_P-helix_param.itp
  python hinge.py  3f7v.pdb  Protein_${chn}.itp  $chn  86  116  >  chain${chn}_TM2_param.itp
  cat chain${chn}_TM1_param.itp chain${chn}_P-helix_param.itp chain${chn}_TM2_param.itp > chain${chn}_param.itp
  python  insert_param.py  Protein_${chn}.itp  chain${chn}_param.itp
done

#
# All the topology files for each chain, namely new_protein_A/B/C/D.itp, need to be combined into a single topology.
python topology_combine.py  4 new_Protein_A.itp new_Protein_B.itp new_Protein_C.itp new_Protein_D.itp


#
# Creating global elastic network (EN) bonds for open and closed structures of KcsA
#python martini.py -f 3f7v-mod.pdb -o system.top -x cg.pdb -dssp dssp -p backbone -ff elnedyn22
#mv Protein_A_P.itp open_Protein_A_P.itp
#python martini.py -f 1k4c.pdb -o system.top -x cg.pdb -dssp dssp -p backbone -ff elnedyn22
#mv Protein_A_P.itp closed_Protein_A_P.itp

#
# Obtaining appropriate EN bonds for KcsA by comparing the open and closed structures of KcsA and select the pairs whose distance varies by over 10% between the two structures
python get_ENs.py open_Protein_A.itp closed_Protein_A.itp > new_ENs.xvg


